### ISSUE TITLE
Define Theia default package for installer

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-example#5]
We need to define what to include in terms of extensions and plugins. 

Initial suggestion:
- Edit, Launch and Debug JS, Typescript and Java Code
- Edit XML and JSON files with syntax highlighting
- Git Integration (Clone, push, pull, commit, checkout, diff)

In addition we could add some features to showcase the flexibility of the Theia platform:
- A code generator based on Xtend
- A textual editor for an XText-based DSL
- A form-based editor (e.g. for editing bug reports)
- A graphical editor or visualization (e.g. editing diagrams for Ecore)

**Comment by koegel** [comment]
We intend to work on this on behalf of ST Microelectronics

**Comment by koegel** [comment]
The current product is configured so it can be used to edit, run and debug JavaScript, Typescript and Java code. We decided to aim for a product that contains all required features to be able to work on the Theia code-base.

**Comment by marcdumais-work** [comment]
> edit, run and debug JavaScript, Typescript and Java code. We decided to aim for a product that contains all required features to be able to work on the Theia code-base.

That's a very good start, and the list of "included by default" extensions can be enhanced at any time.

**Comment by marcdumais-work** [comment]
As an enhancement you can consider including the full set of `vscode built-ins` (minus exceptions). Usually the Microsoft or 3rd party extensions will not re-implement features provided by built-ins. So you might e.g. have a user install the `MS python` extension, have LS support and other advanced features but no syntax highlight because the `vscode.python` extension, that provides the TExtmate grammar, is missing. The user could install it, if they know-to.

**Comment by marcdumais-work** [comment]
cc: @vince-fugnitto

**Comment by koegel** [comment]
> As an enhancement you can consider including the full set of `vscode built-ins` (minus exceptions). Usually the Microsoft or 3rd party extensions will not re-implement features provided by built-ins. So you might e.g. have a user install the `MS python` extension, have LS support and other advanced features but no syntax highlight because the `vscode.python` extension, that provides the TExtmate grammar, is missing. The user could install it, if they know-to.

Good point. How can we include all of them? Is there a list somewhere?

**Comment by marcdumais-work** [comment]
> Good point. How can we include all of them? Is there a list somewhere?

No, I do not think so. I think we should have a way to list them. Would you open an issue on the `vscode-builtin-extensions` repo about this?

For a quick list, see the main repo's example app. The only thing is that their versions have not been updated in a while. 
https://github.com/eclipse-theia/theia/blob/master/package.json#L86-L154

**Comment by koegel** [comment]
Ok, thanks.
And sure, I opened [an issue](https://github.com/theia-ide/vscode-builtin-extensions/issues/40).

**Comment by koegel** [comment]
To add all built-ins to blueprint I also created [an issue](https://github.com/eclipse-theia/theia-example/issues/26) separate from this one.

**Comment by marcdumais-work** [comment]
> > Good point. How can we include all of them? Is there a list somewhere?
> 
> No, I do not think so. 

There is now an easy way to add all built-ins, in one operation - the `built-in extensions pack`:
https://open-vsx.org/extension/eclipse-theia/builtin-extension-pack/1.50.0

There are still things to iron-out, like we'd probably want the extensions to be fetched/installed at build-time rather than runtime. See this draft PR (not to be merged at this time), the first step in using the pack.
https://github.com/eclipse-theia/theia-blueprint/pull/93
